### ISSUE TITLE
iOS build fails on 2021.2.0a16

### ISSUE THREAD

**Issue by lehtiniemi** [hecomi/uLipSync#6]
I was trying to build a project on Unity 2021.2.0a16 on OSX for iOS, but the build seems to fail. It works on Android.

The message I get is, there's some reference to uLipSync in the error:
```
Exception: Unity.IL2CPP.Building.BuilderFailedException: Build failed with 0 successful nodes and 1 failed ones
Annotation: IL2CPP_CodeGen /Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/il2cppOutput/Data
Cmdline: "/Applications/Unity/Hub/Editor/2021.2.0a16/Unity.app/Contents/il2cpp/build/deploy/net5.0/il2cpp" --convert-to-cpp --profiler-report --profiler-output-file="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/buildstate/artifacts/il2cpp_conv_553f.traceevents" --directory="/Users/xxx/Koodaus/xxx/Temp/StagingArea/Data/Managed" --data-folder="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/il2cppOutput/Data" --generatedcppdir="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/il2cppOutput" --symbols-folder="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/il2cppOutput/Symbols" --additional-cpp="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/additionalCppFiles/UnityClassRegistration.cpp" --additional-cpp="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/additionalCppFiles/UnityICallRegistration.cpp" --emit-null-checks --enable-array-bounds-check --code-generation-option=EnableInlining --stats-output-dir="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS/il2cppOutput" --dotnetprofile=unityaot --cachedirectory="/Users/xxx/Koodaus/xxx/Library/Il2cppBuildCache/iOS"
ExitCode: 1
Stdout: 
Error: IL2CPP error for type 'uLipSync.Algorithm/uLipSync.FFT$PostfixBurstDelegate' in assembly '/Users/xxx/Koodaus/xxx/Temp/StagingArea/Data/Managed/uLipSync.dll'
Unity.IL2CPP.HashCodeCollisionException: Hash code collision on value `92CD236A7F26BEF40FEBEADB2CC1C70A3EDAC857`
Existing Item was : `uLipSync.Algorithm/uLipSync.FFT$PostfixBurstDelegate`
Colliding Item was : `uLipSync.Algorithm/uLipSync.FFT$PostfixBurstDelegate`

   at Unity.IL2CPP.HashCodeCache`1.GetUniqueHash(T value) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/HashCodeCache.cs:line 46
   at Unity.IL2CPP.Naming.NamingComponent.ForTypeNameInternal(TypeReference typeReference) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Naming/NamingComponent.cs:line 361
   at Unity.IL2CPP.Naming.NamingComponent.ForTypeNameOnly(TypeReference type) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Naming/NamingComponent.cs:line 91
   at Unity.IL2CPP.Attributes.AttributeNamingExtensions.ForCustomAttributesCacheGenerator(INamingService naming, TypeDefinition typeDefinition) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Attributes/AttributeNamingExtensions.cs:line 12
   at Unity.IL2CPP.Attributes.AttributeSupportCollector.Add(TypeDefinition typeDefinition) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Attributes/AttributeSupportCollector.cs:line 59
   at Unity.IL2CPP.Attributes.AttributeSupportCollector.Collect(TypeDefinition type) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Attributes/AttributeSupportCollector.cs:line 38
   at Unity.IL2CPP.Attributes.AttributeSupportCollector.Collect(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Attributes/AttributeSupportCollector.cs:line 33
   at Unity.IL2CPP.Attributes.AttributeSupportCollector.Collect(MinimalContext context, AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Attributes/AttributeSupportCollector.cs:line 25
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.PerAssembly.AttributeSupportCollection.ProcessItem(GlobalPrimaryCollectionContext context, AssemblyDefinition item) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/PrimaryCollection/Steps.PerAssembly/AttributeSupportCollection.cs:line 16
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.ScheduledItemsStepFunc`5.WorkerWrapper(WorkItemData`3 workerData) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/Steps.Base/ScheduledItemsStepFunc.cs:line 43
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.ContinueWithResultsWorkItem`4.InvokeWorker(Object context, Int32 uniqueId) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 526
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.BaseContinueWorkItem`2.Invoke(Object context, Int32 uniqueId) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 438
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 283

   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, Il2CppCommandLineArguments il2CppCommandLineArguments, BuildingOptions buildingOptions, Boolean throwExceptions) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Program.cs:line 212
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:91)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:792)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:776)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:621)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:272)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:930)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:748)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:693)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:28)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:350)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

```

**Comment by day-dreaming-guy** [comment]
Hey! Did you solve it by chance?
